import { Providers } from '@/app/providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>  {/* Wrap the entire app in Providers */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
